config/routes.rb
LiveBaike::Application.routes.draw do
  require 'api'
  
  devise_for :users

  # namespace :api do
  #   namespace :v1 do
  #     resources :categories, :only => [:index, :create], :format => :json
  #     resources :articles, :only => [:index, :show], :format => :json
  #     get 'articles/category/:id' => 'articles#category'
  #   end
  # end
  
  
  authenticated :user do
    root to: 'home#index'
  end
  
  as :user do
    root to: 'devise/sessions#new'
  end
  
  resources :categories
  
  # match "categories/category:id/articles/published" => "#published", :as => :published_category_articles
  # match "articles/category:id/approved" => "articles#approved", :as => :approved_category_articles
  # match "articles/category:id" => "articles#index", :as => :category_articles
  
  resources :device_infos, only: [:index, :destroy]
  resources :notifications, only: [:index, :new, :create]
  resources :publishes, only: [:index, :new, :create] 
  
  match 'publish/auto_send' => 'publishes#auto_send', via: :get, as: 'auto_send_publish'
  
  resources :articles do
    member do
      put :open
      put :close
    end
    collection do
      get :publish
      get :published
      get :approved
    end
  end
  
  mount LiveBaike::API => '/'
  
end

app/models/article.rb
# coding: utf-8
class Article < ActiveRecord::Base
  attr_accessible :body, :sort, :title, :category_id, :image,:remove_image, :status # 0:待审核, 1:已发布, 2:已审核, 3:未通过
  
  # attr_protected :status
  
  belongs_to :category, :counter_cache => true, :inverse_of => :articles
  has_many :photos
  
  validates_presence_of :title, :body, :category_id
  
  STATES = [['待审核', 0], ['已审核', 2], ['未通过', 3], ['已发布', 1]]
  
  # default_scope order('created_at DESC')
  scope :published, where(:status => 1)
  scope :without_body, except(:body)
  scope :latest, order('access_time DESC')
  scope :approved, where(:status => 2)
  scope :approving, where(:status => 0)
  
  mount_uploader :image, PhotoUploader
  
  def publish
    self.status = 1
    self.access_time = Time.now.to_i
    self.save!
  end
  
  def self.latest_title_list(time, mode)
    
    if time <= 0
      published.latest.without_body
    else
      if mode == 0
        where('access_time < ? and status=1', time).latest.without_body
      else
        where('access_time > ? and status=1', time).latest.without_body
      end
    end
    
  end
  
end

app/controllers/api/v1/articles_controller.rb
# coding: utf-8
module Api
  module V1
    class ArticlesController < Api::ApplicationController
      
      before_filter :restrict_access
      # e86515d5bf9fbc3202e24f5fb3571c7d
      
      def index
        # @categories = Category.where('articles_count > 0')
        # if @categories.any?
        #   render json: { code: 200, message: 'ok', data:@categories.as_json(only: [:id, :name, :color, :articles_count]) }
        # else
        #   render json: { code: 404, message: '没有数据!', data:[] }
        # end
        @articles = Article.select('id, title, created_at').order('created_at DESC').paginate :page => params[:page], :per_page => params[:per_page] || 30
        if @articles.any?
          render json: { code: 200, message: 'ok', data:@articles.as_json(only: [:id, :title, :created_at]) }
        else
          render json: { code: 404, message: "没有数据!", data: [] }
        end
      end
      
      def show
        @article = Article.select('body').where(:id => params[:id])
        if @article
          render json: { code: 200, message: "ok", data: @article.as_json(only: :body) }
        else
          render json: { code: 404, message: "没有数据!", data:[] }
        end
      end
      
      def create
        Article.create!(title:params[:title], body:params[:body], category_id:params[:category_id])
      end
      
      def category
        @category = Category.find(params[:id])
        if @category
          @articles = @category.articles.select('id, title, created_at').order('created_at DESC').paginate :page => params[:page], :per_page => params[:per_page] || 30
          if @articles.any?
            render json: { code: 200, message: 'ok', data:@articles.as_json(only: [:id, :title, :created_at]) }
          else
            render json: { code: 404, message: "没有数据!", data:[] }
          end
        else
          render json: { code: 404, message: "没有此类别!", data:[] }
        end
        
      end
    end
  end
end

app/controllers/articles_controller.rb
# coding: utf-8
class ArticlesController < ApplicationController
  def index
    @articles = Article.approving.without_body.order('id DESC').includes(:category).paginate :page => params[:page], :per_page => 20
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    
    if @article.save
      redirect_to articles_path, notice: "Article was created."
    else
      render :new
    end
  end
  
  def published
    @articles = Article.published.without_body.order('updated_at DESC').includes(:category).paginate :page => params[:page], :per_page => 20
    render :index
  end
  
  def approved
    @articles = Article.approved.without_body.order('updated_at DESC').includes(:category).paginate :page => params[:page], :per_page => 20
    render :index
  end
  
  def publish
    category_id = params[:category_id].to_i
    PublishArticles.random_publish(category_id, 5)
    if category_id.zero?
      redirect_to articles_url
    else
      @category = Category.find(category_id)
      redirect_to @category
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update_attributes(params[:article])
      redirect_to @article, notice: "Article was updated."
    else
      render :edit
    end
  end
  
  def open
    @article = Article.find(params[:id])
    @article.status = 1
    @article.access_time = Time.now.to_i
    @article.save!
    # render :text => 1
  end
  
  def close
    @article = Article.find(params[:id])
    @article.status = 0
    @article.save!
    # render :text => 0
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_url
  end
  
  
  
end

app/helpers/articles_helper.rb
# coding: utf-8
module ArticlesHelper
  def render_article_status(article)
    status = article.status.to_i
    case status
    when 0
      content_tag :span, '待审核', class: 'label label-info'
    when 1
      content_tag :span, '已发布', class: 'label label-success'
    when 2
      content_tag :span, '已审核', class: 'label label-important'
    when 3
      content_tag :span, '未通过', class: 'label label-warning'
    else
      ""
    end
  end
  
  def render_article_open_btn(article)
    
    if article.status.to_i == 0
      label = 'Open'
      path = open_article_path(article)
      flag = false
    else
      label = 'Close'
      path = close_article_path(article)
      flag = true
    end
    
    if flag
      link_to label, path, :method => :put, :confirm => '此操作会影响客户端数据的使用，请慎用！！！', class: 'btn btn-mini', :remote => true
    else
      link_to label, path, :method => :put, :confirm => '你确定要将此数据放开给用户吗？', class: 'btn btn-mini', :remote => true
    end
    
  end
end

app/views/articles/_article.html.erb
<tr id="<%= dom_id article %>">
  <td><%= article.id %></td>
  <td><%= link_to truncate(article.title, length: 50), article %></td>
  <td><%= article.category.name %></td>
  <td><%= render_article_status(article) %></td>
  <td>
      <%= link_to 'Edit', edit_article_path(article), class: "btn btn-mini" %> 
      <%= link_to 'Delete', article_path(article), :method => :delete, confirm: "你确定要删除吗？", class: "btn btn-danger btn-mini" %>
  </td>
</tr>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :enctype =>  "multipart/form-data" } do |f| %>
  <fieldset>
    <legend></legend>
    <%= render 'shared/error_messages', :target => @article %>
    <div class="control-group">
      <%= f.label :title %>
      <div class="controls">
        <%= f.text_field :title %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :body %>
      <div class="controls">
        <%= f.text_area :body, :class => "span6", :style => "height:200px;"%>
      </div>
    </div>
    
    <div class="control-group">
      <%= f.label :status %>
      <div class="controls">
        <%= f.select :status, Article::STATES %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :sort %>
      <div class="controls">
        <%= f.number_field :sort %>
      </div>
    </div>
    
    <% if not @article.image? %>
    <div class="control-group">
      <%= f.label :image, "上传图片" %>
      <div class="controls">
        <%= f.file_field :image %>
      </div>
    </div>
    <% else %>
    <div class="control-group">
      <div class="controls">
        <%= image_tag @article.image.url %>
        <label for='remove_image' class='checkbox'>
          <%= f.check_box :remove_image %> 删除图片 
        </label>
      </div>
      
    </div>
    <% end %>
    
    <div class="control-group">
      <%= f.label :category_id %>
      <div class="controls">
        <%= f.select :category_id, Category.all_categories %>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.submit "提交", class: "btn btn-success" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/articles/_menu.html.erb
<div style="text-align:right;">
  <ul class="submenu unstyled">
      <li <%= "class=active" if action_name == "index" %>><%= link_to '默认', articles_path %></li> /
      <li <%= "class=active" if action_name == "approved" %>><%= link_to '已审核', approved_articles_path %></li> /
      <li <%= "class=active" if action_name == "published" %>><%= link_to '已发布', published_articles_path %></li>
  </ul>
</div>

app/views/articles/close.js.erb
$("#<%= dom_id @article %>").replaceWith("<%= j render @article %>")

app/views/articles/edit.html.erb
<div class="span6 offset2 well">
  <h1>编辑文章</h1>

  <%= render "form" %>
</div>

app/views/articles/index.html.erb
<div class="box">
  <div class="row-fluid">
    <div class="span8"><h2>文章</h2></div>
    <div class="span4"><%= link_to '新建文章', new_article_path, class: "btn btn-primary pull-right" %>
    </div>
  </div>
  <%= render 'articles/menu' %>
  <table class="table table-striped">
    <tr>
      <th>#</th>
      <th>标题</th>
      <th>所属类别</th>
      <th>文章状态</th>
      <th>#</th>
    </tr>
  
    <%= render @articles %>
  
  </table>
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="span6 offset2 well">
  <h1>新建文章</h1>

  <%= render "form" %>
</div>

app/views/articles/open.js.erb
$("#<%= dom_id @article %>").replaceWith("<%= j render @article %>")

app/views/articles/show.html.erb
<div class="well well-small pull-right">
  <%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-primary' %>
  <%= link_to 'Back', category_path(@article.category), :class => 'btn' %>
</div>
<div class="well">
  <div class="text-center">
    <h2><%= @article.title %></h2>

    <em style="color:<%= @article.category.color %>"><%= @article.category.name %></em>
  </div>
  <% if @article.image? %>
  <div class="text-center">
    <%= image_tag @article.image.url %>
  </div>
  <% end %>
  <%= simple_format(@article.body) %>
</div>