config/routes.rb
LiveBaike::Application.routes.draw do
  require 'api'
  
  devise_for :users

  # namespace :api do
  #   namespace :v1 do
  #     resources :categories, :only => [:index, :create], :format => :json
  #     resources :articles, :only => [:index, :show], :format => :json
  #     get 'articles/category/:id' => 'articles#category'
  #   end
  # end
  
  
  authenticated :user do
    root to: 'home#index'
  end
  
  as :user do
    root to: 'devise/sessions#new'
  end
  
  resources :categories
  
  # match "categories/category:id/articles/published" => "#published", :as => :published_category_articles
  # match "articles/category:id/approved" => "articles#approved", :as => :approved_category_articles
  # match "articles/category:id" => "articles#index", :as => :category_articles
  
  resources :device_infos, only: [:index, :destroy]
  resources :notifications, only: [:index, :new, :create]
  resources :publishes, only: [:index, :new, :create] 
  
  match 'publish/auto_send' => 'publishes#auto_send', via: :get, as: 'auto_send_publish'
  
  resources :articles do
    member do
      put :open
      put :close
    end
    collection do
      get :publish
      get :published
      get :approved
    end
  end
  
  mount LiveBaike::API => '/'
  
end

app/models/notification.rb
require 'apns'
require 'open-uri'
# require "grocer"
class Notification < ActiveRecord::Base
  attr_accessible :content
  
  validates_presence_of :content
  
  has_and_belongs_to_many :device_infos
  
  before_create :save_device_infos
  def save_device_infos
    
    
    
    notifications = []
    
    # DeviceInfo.all.each do |device_info|
    #   self.device_infos << device_info
    #   
    #   n = Grocer::Notification.new(
    #     device_token:  device_info.device_token, 
    #     alert:         self.content,
    #     sound:         "default"
    #   )
    #   
    #   # n = APNS::Notification.new(device_info.device_token, :alert => self.content, :sound => "default")
    #   
    #   notifications << n
    # end
    
    # if notifications.any?
    n = APNS::Notification.new("9ae4b3411bb47250f17652dda12591a9c2cbc15b801ec92270853cce80b78de7", :alert => self.content, :sound => "default")
    notifications << n
      
      APNS.send_notifications(notifications)
    # end
    
    # cert = "#{Rails.root}/config/livebaike_cert.pem"
    # 
    # puts cert
    # 
    # pass = "KeKe20130206"
    # 
    # pusher = Grocer.pusher(
    #   certificate: cert,
    #   passphrase:  pass,
    #   gateway:     "gateway.push.apple.com",
    #   port:        2195,
    #   retries:     3
    # )
    # 
    # notifications.each do |notification|
    #   pusher.push(notification)
    # end
    # 
    # feedback = Grocer.feedback(
    #   certificate: cert,
    #   passphrase:  pass,
    #   gateway:     "feedback.push.apple.com",
    #   port:        2196,
    #   retries:     3
    # )
    # 
    # feedback.each do |attempt|
    #   puts "Device #{attempt.device_token} failed at #{attempt.timestamp}"
    # end
    
  end
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.paginate :page => params[:page], :per_page => 30
  end
  
  def new
    @notification = Notification.new
  end
  
  def create
    @notification = Notification.new(params[:notification])
    if @notification.save
      redirect_to notifications_url, notice: 'Notificaiton was successfully created.'
    else
      render 'new'
    end
  end
  
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for @notification do |f| %>
  <fieldset>
    <legend></legend>
    <%= render 'shared/error_messages', :target => @notification %>
    <div class="control-group">
      <%= f.label :content %>
      <div class="controls">
        <%= f.text_field :content %>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.submit "发送通知", class: "btn btn-success", :disable_with => '正在发送...' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/notifications/index.html.erb
<div class="box">
  <div class="row-fluid">
    <div class="span8"><h2>通知</h2></div>
    <div class="span4"><%= link_to '新建通知', new_notification_path, class: "btn btn-primary pull-right" %></div>
  </div>

  <table class="table table-striped">
    <tr>
      <th>#</th>
      <th>通知内容</th>
      <th>创建时间</th>
    </tr>
  
    <% @notifications.each do |notification| %>
    <tr>
      <td><%= notification.id %></td>
      <td width="60%"><%= notification.content %></td>
      <td width="30%"><%= notification.created_at %></td>
    </tr>
    <% end %>
  
    <%= will_paginate @notifications %>
  
  </table>
</div>

app/views/notifications/new.html.erb
<div class="span6 offset2 well">
  <h1>新建通知</h1>

  <%= render "form" %>
</div>